apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
  namespace: fanworkersink
data:
  10_bootstrap.sh: |
    #!/usr/bin/env sh
    set -ex

    echo "[init] esperando a LocalStack (SQS/Dynamo listables)..."
    # Espera a que SQS responda
    until awslocal sqs list-queues >/dev/null 2>&1; do sleep 1; done
    # Espera a que Dynamo responda
    until awslocal dynamodb list-tables >/dev/null 2>&1; do sleep 1; done

    echo "[init] creando DLQ numbers-dlq (idempotente)"
    awslocal sqs create-queue --queue-name numbers-dlq >/dev/null 2>&1 || true

    echo "[init] creando cola numbers (con redrive a DLQ)"
    NUM_DLQ_URL=$(awslocal sqs get-queue-url --queue-name numbers-dlq --query QueueUrl --output text)
    NUM_DLQ_ARN=$(awslocal sqs get-queue-attributes --queue-url "$NUM_DLQ_URL" --attribute-names QueueArn --query 'Attributes.QueueArn' --output text)
    awslocal sqs create-queue \
      --queue-name numbers \
      --attributes "{\"RedrivePolicy\":\"{\\\"deadLetterTargetArn\\\":\\\"$NUM_DLQ_ARN\\\",\\\"maxReceiveCount\\\":\\\"3\\\"}\"}" \
      >/dev/null 2>&1 || true

    echo "[init] creando DLQ numbers-squared-dlq (idempotente)"
    awslocal sqs create-queue --queue-name numbers-squared-dlq >/dev/null 2>&1 || true

    echo "[init] creando cola numbers-squared (con redrive a DLQ)"
    NSQ_DLQ_URL=$(awslocal sqs get-queue-url --queue-name numbers-squared-dlq --query QueueUrl --output text)
    NSQ_DLQ_ARN=$(awslocal sqs get-queue-attributes --queue-url "$NSQ_DLQ_URL" --attribute-names QueueArn --query 'Attributes.QueueArn' --output text)
    awslocal sqs create-queue \
      --queue-name numbers-squared \
      --attributes "{\"RedrivePolicy\":\"{\\\"deadLetterTargetArn\\\":\\\"$NSQ_DLQ_ARN\\\",\\\"maxReceiveCount\\\":\\\"3\\\"}\"}" \
      >/dev/null 2>&1 || true

    echo "[init] creando tabla DynamoDB 'squared-batch-registry' (idempotente)"
    if ! awslocal dynamodb describe-table --table-name squared-batch-registry >/dev/null 2>&1; then
      awslocal dynamodb create-table \
        --table-name squared-batch-registry \
        --attribute-definitions AttributeName=batchId,AttributeType=S AttributeName=seq,AttributeType=N \
        --key-schema AttributeName=batchId,KeyType=HASH AttributeName=seq,KeyType=RANGE \
        --billing-mode PAY_PER_REQUEST
    fi

    echo "[init] esperando estado ACTIVE de 'squared-batch-registry'..."
    while true; do
      STATUS=$(awslocal dynamodb describe-table --table-name squared-batch-registry --query 'Table.TableStatus' --output text 2>/dev/null || echo "CREATING")
      [ "$STATUS" = "ACTIVE" ] && break
      sleep 1
    done

    echo "[init] OK"
