apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: fanworkersink
spec:
  selector:
    app: localstack
  ports:
    - name: http
      port: 4566
      targetPort: 4566
      protocol: TCP
  type: ClusterIP